# docker compose version setting 
version: '3'

services: 
  postgres: 
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INIT_DB_ARGS: --encoding=UTF8 --locale=ja_JP.UTF-8
  
    hostname: postgres
    restart: always
    user: root

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports: 
      - 8000:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    depends_on:
      - postgres
    restart: always

volumes:
  storage:
    external: true
  pgadmin: 
    external: true
  
