version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - DB_LANG=ja_JP
    # image: postgres:alpine
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./storage:/var/lib/postgresql/data
      - ./sh:/docker-entrypoint-initdb.d
      - ./data:/data # db.dumpを配置する

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: